
image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      eval $(command gp env -e)
      mkdir -p /workspace/output
      mkdir -p /workspace/plots
      mkdir -p /workspace/data/aucs
      R -s -e "synapser::synLogin('$SYN_USER','$SYN_TOKEN'); source('00_syn.R')"

vscode:
  extensions:
    - Ikuyadeu.r